name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          set -x
          git fetch --force --tags
          tmp_dir="$(mktemp -d)"
          cd tmp_dir
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz -O - |  | tar -C . -xJf -
          cp $(find . -name 'upx' -type f) /usr/local/bin/upx

      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
