name: test

on:
  workflow_run:
    workflows: ["goreleaser"]
    types:
      - completed
  workflow_dispatch:

jobs:
  instl-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: curl -fsSL instl.sh/daftcreations/gcps/linux | bash
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - run: |
          export PATH=$PATH:$HOME/.local/bin
          if [[ "$(go-nproc)" == "$(nproc)" ]]; then
            exit 0
          else
            exit 1
          fi
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - run: curl -fsSL instl.sh/daftcreations/gcps/macos | bash
        if: ${{ matrix.os == 'macos-latest' }}

      - name: test in ${{ matrix.os }}
        run: |
          export PATH=$PATH:$HOME/.local/bin
          if [[ "$(go-nproc)" == "$(sysctl -n hw.ncpu)" ]]; then
            exit 0
          else
            exit 1
          fi
