name: test

on:
  push:
    paths:
      - "**/**.go"
      - "**/go.**"
      - ".github/workflows/test.yaml"

jobs:
  integration-testing:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with: { go-version: 1.18 }

      - run: go build ./...

      - name: test in ${{ matrix.os }}
        shell: bash
        run: |
          set -x
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            if [[ "$(./go-nproc)" == "$(nproc)" ]]; then
              exit 0
            else
              exit 1
            fi
          fi

          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            if [[ "$(./go-nproc)" == "$(sysctl -n hw.ncpu)" ]]; then
              exit 0
            else
              exit 1
            fi
          fi
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            if [[ "$(./go-nproc)" == "$(echo %NUMBER_OF_PROCESSORS%)" ]]; then
              exit 0
            else
              exit 1
            fi
          fi
